server:
  port: 8080
  
langchain4j:
  open-ai: 
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${DASH_SCOPE_API_KEY}
      model-name: deepseek-v3
      log-requests: true
      log-responses: true
      
  ollama:
    chat-model:
      base-url: http://localhost:11434
      api-key: sk-2741d51d77e64c9caff36b6f63269d18
      model-name: llama3.1
      temperature: 0.8
      timeout: PT60S
      
  community:
    dashscope:
      chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: qwen-max
      embedding-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: text-embedding-v3
      streaming-chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: qwen-plus
spring:
  data:
    mongodb:
      authentication-database: 0
      uri: mongodb://admin:123456@localhost:27017/chat_memory_db?authSource=admin
      username: admin
      password: 123456
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guiguxiaozhi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
logging:
  config: classpath:log4j2.xml